### PR TITLE
test commit

### PR DESCRIPTION
**Pull request by gyselph**
test comment

### CODE REVIEW

**Comment by gyselph** [comment]
another comment

**Comment by pmgysel** [comment]
another comment #2

**Comment by KangolHsu** [comment]
Can you specify the paper you refer in this Ristretto caffe？

**Comment by pmgysel** [comment]
Hi there,
The Ristretto framework was referenced in this ICLR paper: [Hardware-oriented Approximation of Convolutional Neural Networks](https://arxiv.org/abs/1604.03168).
If you have any more questions, feel free to post them on the official Ristretto forum [here](https://groups.google.com/forum/#!forum/ristretto-users).
Best,
Philipp

**Pull request merged**
