### PR TITLE
Merged upstream Windows branch

### PR DESCRIPTION
**Pull request by m1lhaus**
Merged upstream Windows branch from caffe repo. All changes merged without conflict. Compiled using VS2015 and tests passed.

### CODE REVIEW

**Comment by m1lhaus** [comment]
The reason why I am updating Windows branch is that I ported/merged your Ristretto code also to Windows branch. This pull request will follow.

**Comment by pmgysel** [comment]
Thanks for the pull request, it's a great idea to port the Ristretto feature to Windows.

From what I understand from the commit history, it looks like the Ristretto feature is already in your branch (commit 14670d7), is this right?

**Comment by m1lhaus** [comment]
Yes, it is. I wanted you update the windows branch first. I just exported changes you did from master as a patch and merged it with my windows branch. I am gonna create another pull request just for better history tracking once you merge.

**Comment by pmgysel** [comment]
Sure thing, I'm looking forward to the pull request which will complete the Windows Ristretto feature.

**Comment by m1lhaus** [comment]
It seems I messed up during this pull request where I accidentally hit "comment and close" and when I did re-open pull request, it actually took all changes with also ristretto code, so now it's already in the repo. It wasn't my initial plan, but never mind :-/

I tested the example scripts you provided for quantization and all ran fine. I don't have GPU on my Windows notebook so I did not run full Imagenet quantization/finetunning, just few iterations. So just FYI.

**Comment by pmgysel** [comment]
Ok I see. So is this Ristretto Windows feature already working or are there still commits from you in the future?

**Comment by m1lhaus** [comment]
It is working, at least it's not crashing or anything so far. If I find some issues in future, I'll commit a fix.

**Pull request merged**
